imports:
    - javascript
    - php

filter:
    excluded_paths: [js/vendor/*, tests/]
    dependency_paths:
        - vendor/christophwurst/nextcloud
        - vendor/doctrine/dbal
        - 3rdparty/getID3/getid3
        - stubs

# Code coverage is not collected at the moment to speed up the Scrutinizer analysis, especially on the
# private fork of the project where there is no Travis running the tests.
#tools:
#    external_code_coverage:
#        timeout: 300    # Timeout in seconds, 5 minutes
#        runs: 2         # Scrutinizer waits for the first 2 coverage submissions (unit & integration)

build:
    image: default-bionic
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
