# Jekyll configuration
repository: rello/musicnc
theme: jekyll-theme-cayman
timezone: Europe/Berlin
name: "Music"
title: "Music"
description: "Audio Player for Nextcloud and ownCloud"
url: "https://rello.github.io/musicnc"
author: "S P A R K"
