# Jekyll configuration
repository: satthuno999/musicnc
theme: jekyll-theme-cayman
timezone: Europe/Berlin
name: "Music"
title: "Music"
description: "Audio Player for Nextcloud and ownCloud"
url: "https://cloudkma.online"
author: "S P A R K"
